import { Company } from "./Company";
import { Maps } from "./Maps";
import { User } from "./User";
const user = new User();
console.log(user);
const company = new Company();
console.log(company);
const map = new Maps("map");
map.addMarker(user);
map.addMarker(company);
